repositories:
    - name :        Test Repository
      url :         http://macfuse.googlecode.com/svn/
      path :        trunk/
      username :    guest
      password :    guest 

options:
    limit :         10